from PIL import Image
import numpy as np

import os
import glob

# Dataset generated to train the network
filestraining = glob.glob(r'filea/*')
# Dataset generated to evaluate the network performance
fileseval = glob.glob(r'fileb/*')
# Dataset generated to test the network with a single character
filesingle = glob.glob(r'filea/00000.png')


def generate_array(inputdir,outputfile):
	out= np.array([], dtype=np.uint8)
	filenum=1
	count=0
	for name in inputdir:
			#If files were generated by main.py,
			#name[6:10] should be the label
			label = name[6:10]
			print(label)
			
			count = count + 1
			
			im = Image.open(name)
			rgb_im = im.convert('RGB')
			im = (np.array(rgb_im))

			r = im[:,:,0].flatten()
			g = im[:,:,1].flatten()
			b = im[:,:,2].flatten()
			
			gray = 0.2989 * r + 0.5870 * g + 0.1140 * b

			labelfin= []
			labellist=np.array( list(label),np.uint8)
			
			for charac in np.nditer(labellist):
						charac2=charac+48
						labelfin.append(charac2)
			
			out=np.r_[out,np.array( list(labelfin) + list(gray),np.uint8)]
			
			if count==50000:
						out.tofile(outputfile+"_"+str(filenum)+".bin")
						count = 0
						filenum = filenum + 1
						out= np.array([], dtype=np.uint8)
			
	out.tofile(outputfile+"_"+str(filenum)+".bin")
	return
	
#There lines should be commented if you don't want to generate every file
generate_array(filestraining,"training")
generate_array(fileseval,"verify")
#generate_array(filesingle,"single")
